from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AdminLoginView,
    AdminStatsView,
    AdminTransfersView,
    AdminPlayerDetailView,
    AdminPlayersView,
    AdminUserDetailView,
    AdminUsersView,
    AnalyticsSummaryView,
    DirectLoginView,
    EmailTokenObtainPairView,
    GoogleLoginView,
    NotificationsView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PlayerSearchView,
    RegisterView,
    Request2FAView,
    RequestSignupCodeView,
    TransferHistoryView,
    UserDashboardView,
    UserTeamView,
    UserTransferMarketView,
    UserTransferSubmitView,
    Verify2FAView,
    WatchlistPlayerDetailsView,
    WatchlistView,
    WatchlistRecentMatchesView,
    WeeklyLeaderboardView,
    ProfileUpdateView,
    ProfilePictureUploadView,
    ChangePasswordView,
    LeaderboardView,
    LiveScoresView,
    MatchDifficultyView,
    SyncPointsView,
    SimulateLastMatchweekView,
    TopAttackersView,
    UserMatchDetailView,
    UserMatchStatsView,
    UserMatchesView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('register/code/', RequestSignupCodeView.as_view(), name='register_code'),
    path('auth/login/', DirectLoginView.as_view(), name='direct_login'),
    path('auth/admin/login/', AdminLoginView.as_view(), name='admin_login'),
    path('auth/google/', GoogleLoginView.as_view(), name='google_login'),
    path('auth/password-reset/request/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('auth/password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('token/', EmailTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/2fa/request/', Request2FAView.as_view(), name='2fa_request'),
    path('auth/2fa/verify/', Verify2FAView.as_view(), name='2fa_verify'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('admin/stats/', AdminStatsView.as_view(), name='admin_stats'),
    path('admin/users/', AdminUsersView.as_view(), name='admin_users'),
    path('admin/users/<str:user_id>/', AdminUserDetailView.as_view(), name='admin_user_detail'),
    path('admin/players/', AdminPlayersView.as_view(), name='admin_players'),
    path('admin/players/<int:player_id>/', AdminPlayerDetailView.as_view(), name='admin_player_detail'),
    path('admin/transfers/', AdminTransfersView.as_view(), name='admin_transfers'),
    path('user/analytics/', AnalyticsSummaryView.as_view(), name='user_analytics'),
    path('user/dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('user/team/', UserTeamView.as_view(), name='user_team'),
    path('user/analytics/top-attackers/', TopAttackersView.as_view(), name='user_top_attackers'),
    path('user/transfers/market/', UserTransferMarketView.as_view(), name='user_transfer_market'),
    path('user/matches/', UserMatchesView.as_view(), name='user_matches'),
    path('user/matches/<int:match_id>/', UserMatchDetailView.as_view(), name='user_match_detail'),
    path('user/matches/<int:match_id>/statistics/', UserMatchStatsView.as_view(), name='user_match_stats'),
    path('user/matches/live/', LiveScoresView.as_view(), name='user_live_scores'),
    path('user/matches/difficulty/', MatchDifficultyView.as_view(), name='user_match_difficulty'),
    path('players/search/', PlayerSearchView.as_view(), name='player_search'),
    path('players/', UserTransferMarketView.as_view(), name='players'),
    path('user/transfers/submit/', UserTransferSubmitView.as_view(), name='user_transfer_submit'),
    path('user/transfers/history/', TransferHistoryView.as_view(), name='user_transfer_history'),
    path('user/watchlist/', WatchlistView.as_view(), name='user_watchlist'),
    path('watchlist/<int:player_id>/details/', WatchlistPlayerDetailsView.as_view(), name='watchlist_player_details'),
    path('user/watchlist/<int:player_id>/details/', WatchlistPlayerDetailsView.as_view(), name='user_watchlist_player_details'),
    path('user/watchlist/<int:player_id>/recent-matches/', WatchlistRecentMatchesView.as_view(), name='user_watchlist_recent_matches'),
    path('user/notifications/', NotificationsView.as_view(), name='user_notifications'),
    path('user/profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('user/profile/picture/', ProfilePictureUploadView.as_view(), name='profile_picture_upload'),
    path('user/password/change/', ChangePasswordView.as_view(), name='password_change'),
    path('user/leaderboard/', LeaderboardView.as_view(), name='user_leaderboard'),
    path('user/leaderboard/weekly/', WeeklyLeaderboardView.as_view(), name='user_weekly_leaderboard'),
    path('user/sync-points/', SyncPointsView.as_view(), name='user-sync-points'),
    path('user/simulate-last-matchweek/', SimulateLastMatchweekView.as_view(), name='simulate-last-matchweek'),
]
